flags:
    source-hide:        Aenean-non-orci
    source-comment:     Integer-nec-eros
    response-header:    Integer-luctus-felis
    request-header:     Quisque-placerat-commodo
    static-csv:         Phasellus-blandit-turpis
    admin-page:         Mauris-fermentum-massa
    not-found:          Maecenas-sit-amet
    cookie:             Morbi-mollis-bibendum
    user-agent:         Morbi-at-turpis
    image:              Nullam-imperdiet-in
    hidden-form-index:  Aliquam-eleifend-ornare
    url-sql-inject:     In-vitae-laoreet
    href-redirect:      Aliquam-erat-volutpat
    xsrf:               Vestibulum-sagittis-sagittis
    favicon:            flaaaag
    weak-old-db:        weak-old-db        

config:
    adminToken: 'bf283af425336bc4ac6bd3b29b746d61'  # MD5 for "VotaiTest.2023"
    host: localhost                                 # Dev: not in WSGI
    port: 5000                                      # Dev: not in WSGI
